[package]
name = "fittle-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
fittle-core = { path = "../crates/fittle-core" }
fittle-image = { path = "../crates/fittle-image" }

[[bin]]
name = "header"
path = "fuzz_targets/header.rs"
test = false
doc = false
bench = false

[[bin]]
name = "rice"
path = "fuzz_targets/rice.rs"
test = false
doc = false
bench = false

[[bin]]
name = "edit"
path = "fuzz_targets/edit.rs"
test = false
doc = false
bench = false
