[package]
name = "fittle-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
fittle-astro.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
sha2 = "0.10"


[dev-dependencies]
proptest = "1"
tempfile = "3"
