[package]
name = "fittle-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "fittle"
path = "src/main.rs"

[dependencies]
fittle-core.workspace = true
fittle-image.workspace = true
fittle-mcp.workspace = true
fittle-scan.workspace = true
clap.workspace = true
owo-colors = { version = "4", features = ["supports-colors"] }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
insta.workspace = true
tempfile = "3"
serde_json.workspace = true
