[package]
name = "fittle-image"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
fittle-core.workspace = true
fittle-astro.workspace = true
thiserror.workspace = true
serde.workspace = true
rayon = "1"
half = "2"
png = "0.18"
jpeg-encoder = "0.7"
image-webp = "0.2"
tiff = "0.11"
flate2 = "1"

[dev-dependencies]
fitsrs.workspace = true
fittle-scan.workspace = true
serde_json.workspace = true
