// Generate ui/styles/tokens.css from docs/design-system/tokens.json (the
// published Fittle style guide). Run: node scripts/tokens.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "../../docs/design-system/tokens.json");
const out = join(here, "../ui/styles/tokens.css");
const t = JSON.parse(readFileSync(src, "utf8"));

const themes = t.color.themes.map((x) => x.id);
const block = (theme) =>
  t.color.tokens
    .map((c) => {
      const v = typeof c.value === "string" ? c.value : (c.value[theme] ?? c.value[themes[0]]);
      return `  --${c.name}: ${v};`;
    })
    .join("\n");
const flat = ["spacing", "radius", "shadow", "duration", "layout"]
  .flatMap((f) => (t[f]?.tokens ?? []).map((x) => `  --${x.name}: ${x.value};`))
  .join("\n");
const fam = Object.entries(t.type.families)
  .map(([k, v]) => `  --font-${k}: ${v};`)
  .join("\n");

const css = `/* GENERATED by app/scripts/tokens.mjs from docs/design-system/tokens.json. Do not edit. */
:root, [data-theme="${themes[0]}"] {
  color-scheme: dark;
${block(themes[0])}
}
${themes
  .slice(1)
  .map((th) => `[data-theme="${th}"] {\n  color-scheme: ${th === "light" ? "light" : "dark"};\n${block(th)}\n}`)
  .join("\n")}
:root {
${flat}
${fam}
}
`;
writeFileSync(out, css);
console.log(`wrote ${out}`);
